version: 2
jobs:
  build:
    environment:
      PROJECT: "task-cinema-weekly"
    working_directory: ~/app
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependency-{{ checksum "package.json" }}
          - v1-dependency-
      - run: npm i
      - run: npm run eslint
      - save_cache:
          paths:
            - node_modules
          key: v1-dependency-{{ checksum "package.json" }}
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER --password $DOCKER_PASS container.touno.io
      - run: docker build -t container.touno.io/$PROJECT:latest .
      - run: PACKAGE_VERSION=v$(cat package.json | grep version | head -1 | sed 's/[version :\",]//g') && docker tag container.touno.io/$PROJECT:latest container.touno.io/$PROJECT:$PACKAGE_VERSION 
      - run: docker push container.touno.io/$PROJECT
